apiVersion: networking.k8s.io/v1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: etl-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  rules:
  - host: "{{ .Values.ingressenvname }}.{{ .Values.ingresshost }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: etl-nginx-service
            port:
              number: 8080
