apiVersion: v1
kind: Service
metadata:
  name: etl-nginx-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: etl-nginx
  ports:
    - name: etl-nginx
      port: 80
      targetPort: 8080
